baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Professor Portfolio"
theme = "PaperMod"

[params]
author = "Your Name"
defaultTheme = "light"
ShowReadingTime = false
ShowShareButtons = false

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Research"
url = "/research/"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 3

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 4

[[menu.main]]
name = "Awards"
url = "/awards/"
weight = 5

[[menu.main]]
name = "Workshops"
url = "/workshops/"
weight = 6

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 7
